### ISSUE TITLE
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in vendor/php-http/curl-client/src/Client.php on line 86

### ISSUE THREAD

**Issue by kitalik** [mailerlite/mailerlite-api-v2-php-sdk#1]
When trying to use the code examples in your documentation gives an error.
Code example:
    $mailerliteClient = new \MailerLiteApi\MailerLite('your-api-key');
    var_dump($mailerliteClient);
    $groupsApi = $mailerliteClient->groups();
    $groups = $groupsApi->get(); // returns array of groups

**Comment by oleksiimelnichenko** [comment]
In order to use this library you need to have at least PHP 5.4 version.

**Comment by justinasposiunas** [comment]
@kitalik you need to use at least PHP 5.5 like @oleksiimelnichenko mentioned before.

**Comment by kitalik** [comment]
Yes, thank you all!
