### ISSUE TITLE
Without Composer

### ISSUE THREAD

**Issue by gonzalesc** [mailerlite/mailerlite-api-v2-php-sdk#14]
Hi:
Do you have example to do it without composer?

I dowload [this file](http://bit.ly/ml-php-sdk-0_1_10) and put it in the root folder and it says:
Fatal error: Uncaught Error: Class 'MailerLiteApi\Common\RestClient' not found..

Regards

**Comment by dominykasmailer** [comment]
Hello,

Sorry for the long wait...

Have you added:
require 'vendor/autoload.php'; in the file before using the RestClient?
