### ISSUE TITLE
How to add multiple users to multiple groups with one request

### ISSUE THREAD

**Issue by iMojtaba** [mailerlite/mailerlite-api-v2-php-sdk#16]
Hi, 
Is that possible to add multiple users to multiple groups with one request through API?
thanks

**Comment by dominykasmailer** [comment]
Hello @iMojtaba ,

It is currently impossible to add multiple users to multiple groups with a single API request.

We are not really planning to add this feature.

But we do offer adding multiple users to a single group with one request:
https://developers.mailerlite.com/reference#add-many-subscribers

Let me know if you require any more assistance.

**Comment by iMojtaba** [comment]
Thank you dominykasmailer
