### ISSUE TITLE
How to add user via API ?

### ISSUE THREAD

**Issue by andreybolonin** [mailerlite/mailerlite-api-v2-php-sdk#2]
In API v1 I see this function https://docs.mailerlite.com/pages/subscribers#post

which is used to creation new user.

In new API we will never have this functionality?

Or you planning this feature in roadmap?

p.s.
I asked because we getting our leads in our crm. 
And we should have some way to synchronize this leads in crm with Mailerlite.

**Comment by justinasposiunas** [comment]
This feature is still available ant it will be. It may differ a little bit but everything can be found here: http://developers.mailerlite.com/docs/add-single-subscriber

**Comment by andreybolonin** [comment]
Oh!

Thank you. I missed them in API v2.
