### ISSUE TITLE
How can I send custom values?

### ISSUE THREAD

**Issue by davidperezgar** [mailerlite/mailerlite-api-v2-php-sdk#22]
I'm using addSubscriber method, but I'd like to send custom values. How will it be the method?

**Comment by davidperezgar** [comment]
Hello, please reply

**Comment by Fateslayer** [comment]
This is the method declaration -
`addSubscriber($groupId, $subscriberData = [], $params = []);`
I think you can pass your data as an argument in the second parameter like -
`$groupId = 7;`
`$customData = array("name" => "minecraft");`
`$groupsApi->addSubscriber($groupId, $customData);`

**Comment by davidperezgar** [comment]
Hello, 
Actually I've used an array with:
array(
'name'=>'Name',
'email'=>'email@domain.com',
'fields'=>array(
'field1'=>'value1',
'field2'=>'value2'
)
);

And so on...

**Comment by Fateslayer** [comment]
So it didn't work?
