### ISSUE TITLE
Can't install with php-http/curl-client 2.0

### ISSUE THREAD

**Issue by girvydas** [mailerlite/mailerlite-api-v2-php-sdk#24]
Composer requirements could not be resolved to an installable set of packages.
    - Installation request for mailerlite/mailerlite-api-v2-php-sdk ^0.2.3 -> satisfiable by mailerlite/mailerlite-api-v2-php-sdk[0.2.3].
    - Conclusion: remove php-http/curl-client 2.0.0
    - Conclusion: don't install php-http/curl-client 2.0.0
    - mailerlite/mailerlite-api-v2-php-sdk 0.2.3 requires php-http/curl-client ^1.4 -> satisfiable by php-http/curl-client[1.7.x-dev, v1.4.0, v1.4.1, v1.4.2, v1.5.0, v1.5.1, v1.6.0, v1.6.1, v1.6.2, v1.7.0, v1.7.1].

Please update requirements to support newer version of curl-client.

**Comment by dominykasmailer** [comment]
Hello @girvydas,

We will look into this dependency issue let you know how we can resolve it

Thanks for reporting!

Dominykas
MailerLite

**Comment by dominykasmailer** [comment]
Please try again with new version.
