### ISSUE TITLE
Tests fails while adding subscriber

### ISSUE THREAD

**Issue by girvydas** [mailerlite/mailerlite-api-v2-php-sdk#25]
No changes added to code but, test (MlTestCase.php:38) throws "Trying to get property 'imported' of non-object"
Maybe it's demo account problem?

**Comment by dominykasmailer** [comment]
Hello again @girvydas,

I will look at this with the dependency issue and let you know my findings 🤝 

Dominykas
MailerLite

**Comment by dominykasmailer** [comment]
This should not be relevant any more but the problem was that the import was not working correctly
