### ISSUE TITLE
Documentation unclear: addContent() method

### ISSUE THREAD

**Issue by ZainRizvi** [mailerlite/mailerlite-api-v2-php-sdk#27]
Can you please describe the expected format of `$contentData` in the following line?

https://github.com/mailerlite/mailerlite-api-v2-php-sdk/blob/2f4b874d245473bd964183e52a91a906d591c8c6/src/Api/Campaigns.php#L19

It seems like it should be a html string yet the parameter is an array.

For context: My use case is to be able to create a new campaign and send emails when an external event is triggered

Also, does calling this method override any existing data?

**Comment by dominykasmailer** [comment]
hello @ZainRizvi ,

The array must contain `html` and `plain`. HTML is self explanatory and `plain` is the text version of your email.

In the new version of SDK the array is forced to have those keys:

```PHP
public function addContent(int $campaignId, array $contentData)
    {
        if ( ! array_key_exists('html', $contentData)) {
            throw new MailerLiteSdkException("HTML must be provided");
        }
        if ( ! array_key_exists('plain', $contentData)) {
            throw new MailerLiteSdkException("Plain text must be provided");
        }
```
