### ISSUE TITLE
Items Protected

### ISSUE THREAD

**Issue by sfeldersiprep** [mailerlite/mailerlite-api-v2-php-sdk#28]
Just started to experiment with your API SDK but all my results are coming back protected. I also can't seem to find any documentation on this. Am I missing something?

My code:
```
$path = '/var/www/html/mailerlite/vendor/autoload.php';
require $path;
$mailerliteClient = new \MailerLiteApi\MailerLite($api_key);
$groupsApi = $mailerliteClient->groups();
$groups = $groupsApi->get(); // returns array of groups
```
Thanks for any suggestions!

**Comment by dominykasmailer** [comment]
Hello @sfeldersiprep,

When doing `$groupsApi->get()` we're returning an instance of `MailerLiteApi\Common\Collection`.
It does indeed have protected items but that's the design of it.

I can be accessed like a simple array:
```PHP
$groups = $groupsApi->get();
var_dump($groups[0]);
```

If you want to have a array and not a collection, you can do:
```PHP
$groups = $groupsApi->get()->toArray();
```

Hope this answers your question.
