### ISSUE TITLE
Fatal error: Cannot redeclare Clue\StreamFilter\append()

### ISSUE THREAD

**Issue by louisgan** [mailerlite/mailerlite-api-v2-php-sdk#36]
**Background:**

When another package includes clue/php-stream-filter package, a fatal error happens.

**Solution:**

Upgrade clue/stream-filter package to use version 1.4.1

**Source:**
https://github.com/clue/php-stream-filter/issues/26
https://github.com/php-http/message/commit/f48e96f3deb35d4b4387a0711083ad7f917eaf13

**Comment by dominykasmailer** [comment]
Please try again with new version.
