### ISSUE TITLE
Can not install in laravel 7 project

### ISSUE THREAD

**Issue by vimalmistry** [mailerlite/mailerlite-api-v2-php-sdk#37]
I tried with Php 7.2 and 7.4, Same result. 

![Screenshot 2020-05-18 at 4 03 23 PM](https://user-images.githubusercontent.com/3993163/82203654-362b4f80-9921-11ea-9e85-c374a4c9565a.png)

**Comment by vimalmistry** [comment]
This is issue is related with **php-http/httplug** version. Please update plugin version.

**Comment by we-plast** [comment]
Same here! Even when I update httplug  to latest version I still get the error. 

![image](https://user-images.githubusercontent.com/65532840/83499173-37ca4b00-a4bd-11ea-9048-d84c062b38a0.png)

**Comment by dstuecken** [comment]
This issue is a duplicate, See #31

**Comment by dominykasmailer** [comment]
Please try again with new version.
