### ISSUE TITLE
wrong response for groups subscriber belongs to

### ISSUE THREAD

**Issue by shayan-ys** [mailerlite/mailerlite-api-v2-php-sdk#4]
Thanks for great wrapper,
but it has a problem in returning groups subscribers belongs to, it should return an array of groups which is correct for MailerLite API ( I had to send request myself without the wrapper ) but wrapper's response is not what expected ( object of "account" returns instead )
[MailerLite doc](https://developers.mailerlite.com/docs/groups-subscriber-belongs-to)

**Comment by justinasposiunas** [comment]
@shayan-ys this issue was fixed before, [associated commit is here](https://github.com/mailerlite/mailerlite-api-v2-php-sdk/commit/74be10418742b440b41e3049affdf0a1fe007cf4) try to update our wrapper:)
