### ISSUE TITLE
Calls to API are failing due to 301 moved error

### ISSUE THREAD

**Issue by felicityheaton** [mailerlite/mailerlite-api-v2-php-sdk#40]
MailerLite recently emailed asking everyone to update to HTTPS instead of HTTP for the calls to the API. Since then, the calls to the API using the files provided and code that worked fine before now fail. When querying the subscriber list for example, it throws a 301 moved error stating that the document has been moved to a new URL.

MailerLite have told me it's down to ME to change all these API files from GitHub which doesn't seem right to me. I don't particularly feel I should be the one tinkering to update files that MailerLite themselves have provided.

Is there any possible chance you can update the GitHub files so it now works with HTTPS and fixes this error?

**Comment by jedzura** [comment]
I have the same problem.

**Comment by dominykasmailer** [comment]
Hello @felicityheaton , `http` was used in old versions of this PHP SDK, so the only possible problem is that you're using a old version, please update here: https://github.com/mailerlite/mailerlite-api-v2-php-sdk#getting-started
