### ISSUE TITLE
PHP 8.0. is not supported

### ISSUE THREAD

**Issue by driule** [mailerlite/mailerlite-api-v2-php-sdk#45]
The new PHP version is not supported, please upgrade your client to support PHP 8.0. version. This issue blocks the whole project upgrade.

https://github.com/mailerlite/mailerlite-api-v2-php-sdk/blob/master/composer.json
```
    "require": {
        "php" : "^7.1",
        ...
    },
```

**Comment by thdebay** [comment]
Any news on this?

**Comment by nklmilojevic** [comment]
Hey all! Apologies for keeping you waiting. We have merged the support for PHP8 in our latest release (0.3.2).
