### ISSUE TITLE
Double opt-in for API

### ISSUE THREAD

**Issue by bajki** [mailerlite/mailerlite-api-v2-php-sdk#46]
How to use this option?

Right now when i add subscriber it's active but i want to user confirm email.

Thanks

**Comment by johnkelesidis** [comment]
You can enable double opt-in confirmations from the subscribe settings menu.
![image](https://user-images.githubusercontent.com/72185528/127848376-7d2029df-4816-4623-aa9a-de9f5c1df153.png)

Then, all subscribers that are added through the API will receive a confirmation email.
