### ISSUE TITLE
Support php 8

### ISSUE THREAD

**Issue by nezaboravi** [mailerlite/mailerlite-api-v2-php-sdk#47]
Please upgrade to support php8
It became useless

**Comment by vacoup95** [comment]
Yes, please update to PHP 8 (well at least the composer file). If you use --ignore-platform-reqs on composer it still seems to work fine.

**Comment by richtechteam** [comment]
when going to upgrade to support php8?

**Comment by ilidan85** [comment]
Would be great to see it working with php8 guys :)

**Comment by MarGul** [comment]
There is a [PR](https://github.com/mailerlite/mailerlite-api-v2-php-sdk/pull/51) for it already but needs to be approved

**Comment by ldiebold** [comment]
Anything blocking this? php8 would be great :)

**Comment by nklmilojevic** [comment]
Hey all! Apologies for keeping you waiting. We have merged the support for PHP8 in our latest release (0.3.2).
