### ISSUE TITLE
Class Request not found

### ISSUE THREAD

**Issue by eugenealegiojo** [mailerlite/mailerlite-api-v2-php-sdk#5]
Fatal error: Class 'MailerLiteApi\Common\Request' not found in \Common\RestClient.php on line 96

It looks like it's still using `GuzzleHttp\Psr7\Request` even if `$this->httpClient` has been defaulted to null.
Any ideas on this?

Thanks.

**Comment by medutis** [comment]
Hey @eugenealegiojo, did you manage to solve it on your own?

**Comment by eugenealegiojo** [comment]
No, I'm not using a composer for dependencies so I decided to write my own.
