### ISSUE TITLE
Issue with "Use your preferred HTTP client" section of readme.

### ISSUE THREAD

**Issue by dontfeedthecode** [mailerlite/mailerlite-api-v2-php-sdk#56]
`$mailerliteClient = new \MailerLiteApi\Mailerlite('your-api-key', $guzzleClient);`

There is a case sensitivity issue here, this should be:

`$mailerliteClient = new \MailerLiteApi\MailerLite('your-api-key', $guzzleClient);`

Copy/pasting this example as-is will work in a case-insensitive environment (e.g. Windows) but break once pushed to a case-sensitive environment for testing or production.

**Comment by johnkelesidis** [comment]
Hi,

Readme updated. Thanks!
