### ISSUE TITLE
Tests are not working anymore

### ISSUE THREAD

**Issue by skoudoro** [mailerlite/mailerlite-api-v2-php-sdk#57]
Hi all,

I am maintaining a [python wrapper of the Mailerlite API](https://github.com/skoudoro/mailerlite-api-python)

It seems that the public API key ([here](https://github.com/mailerlite/mailerlite-api-v2-php-sdk/blob/9fb6b8adb3b0dd9eb964ba5169b229516c73fd78/tests/bootstrap.php#L6)) does not work anymore. It returns `{"error":{"code":302,"message":"API-Key Unauthorized"}}`. 

This is breaking all my tests and the tests in this repo also. I can not use my personal Developer API key. 

Is there any alternative?

Thanks in advance for the feedback!

**Comment by johnkelesidis** [comment]
Hi,

I'm afraid not. The intended use is for the developer to add their own API key and run the tests.

**Comment by skoudoro** [comment]
No problem, Thank you for the feedback. I used a workaround.

And, I planned to archive my python wrapper repo since there is now an official one.
