### ISSUE TITLE
import limitation

### ISSUE THREAD

**Issue by iMojtaba** [mailerlite/mailerlite-api-v2-php-sdk#6]
Hi, 
I want sync more than 30.000 email with mailerlite. 
i read your document and find [import method](https://developers.mailerlite.com/reference#add-many-subscribers)
now i have one question: how many email can i send through this method ? 
thanks.

**Comment by medutis** [comment]
Hello iMojtaba, it's hard to tell, cause it depends on the size of request payload - it might hit server limits. I recommend you importing subscribers in chunks, let's say 1000 every chunk, and be sure to check response message to know exactly if it went successfully
