### ISSUE TITLE
Where is the "group ID"

### ISSUE THREAD

**Issue by Benthediver99** [mailerlite/mailerlite-api-v2-php-sdk#62]
I feel like I'm missing something.  I'm not getting successful subscription using the php sdk.  There is no group ID available on the mailerlite website when I look under subscribers.  Has the process changed or where do I find group ID?

**Comment by johnkelesidis** [comment]
Hi,

Use this endpoint to get the groups a subscriber belongs to https://developers-classic.mailerlite.com/reference/groups-subscriber-belongs-to
