### ISSUE TITLE
Can't use this library with PHP 7.4 (or just 7.x)

### ISSUE THREAD

**Issue by contactjavas** [mailerlite/mailerlite-api-v2-php-sdk#66]
### What is the problem?
This repo says it requires at least PHP version `7.1`. But after doing fresh install of this component, the Mailerlite's dependencies require at least PHP version `8.1`
- [symfony/deprecation-contracts](https://github.com/symfony/deprecation-contracts)
- [symfony/options-resolver](https://github.com/symfony/options-resolver)

Is the `7.1` requirement for this Mailerlite API still valid?

### How to reproduce:
- Switch to PHP 7.x (7.4 in my use-case)
- Do fresh install of this Mailerlite API v2 PHP SDK
- Add a new subscriber to a group

### Code that can be used for faster reproducing:
```php
$mailerlite_api_key = '';
$mailerlite_group_id = '';

$mailerlite_group_api = ( new \MailerLiteApi\MailerLite( $mailerlite_api_key ) )->groups();

$mailerlite_subscriber = [
    'email'  => $this->email,
    'fields' => [
        'name' => $this->name,
    ],
];

$response = $mailerlite_group_api->addSubscriber( $mailerlite_group_id, $mailerlite_subscriber );
```

**Comment by johnkelesidis** [comment]
Hi,

This has been fixed a while ago. The php requirements are now `^7.1 || ^8.0`
