### ISSUE TITLE
Error on removing subscription

### ISSUE THREAD

**Issue by luis-dias-eae** [mailerlite/mailerlite-api-v2-php-sdk#69]
Hello,

When trying to remove a subscription, having already identified it and using the id i am using the delete method passing the id as a parameter.
The result is the following error: "Endpoint not found"

Can you please provide some help?

I am using Laravel 8.

Regards,

Luis Dias

**Comment by johnkelesidis** [comment]
Hey,

There's no delete method in the Subscribers resource in the sdk.

Also, there's no DELETE endpoint for subscribers (https://developers-classic.mailerlite.com/reference).
Try updating the subscriber type to `unsubscribed` instead.
