### ISSUE TITLE
Campaigns GET endpoint not found

### ISSUE THREAD

**Issue by Jeroenhulshof** [mailerlite/mailerlite-api-v2-php-sdk#70]
When i want to fetch all campaigns through the API, i get the ```endpoint not found``` error. 

```
    public function __construct()
    {
        $this->instance = new \MailerLiteApi\MailerLite('credentials');
    }

    public function getCampaigns()
    {
        $response = $this->instance->campaigns()->get();
    }
```

**Comment by ranaroussi** [comment]
@Jeroenhulshof - any luck there?

**Comment by Jeroenhulshof** [comment]
@ranaroussi nope. Not yet

**Comment by ranaroussi** [comment]
Just got this from their support:

> The reason behind this, is that campaign endpoints don't work yet for the new app.
> 
> Our developers are working on implementing it, so in the nearest future, those endpoints will be working with the new API.

☹️

**Comment by Jeroenhulshof** [comment]
Very nice! I'll be waiting :) thanks for your reply @ranaroussi

**Comment by sergeynilov** [comment]
I got the same error. If there is a hope it to be fixed? I lee last updates on the project were 2 years ago ...

**Comment by SaijoGeorge** [comment]
any updates on this?

**Comment by johnkelesidis** [comment]
Sorry, this fell through the cracks. This was implemented back in April.
