### ISSUE TITLE
How to use your Where filter?

### ISSUE THREAD

**Issue by a-frolov-paysera** [mailerlite/mailerlite-api-v2-php-sdk#72]
It looks really strange
How to use it, if i want to get groups with names like some string ?

https://github.com/mailerlite/mailerlite-api-v2-php-sdk/blob/6c13e721511f5045770115bfbc754fbe3a7bb27a/src/Common/ApiAbstract.php#L166

**Comment by johnkelesidis** [comment]
Hi, I'm afraid this hasn't been implemented.
