### ISSUE TITLE
Fatal Error on adding new subscriber

### ISSUE THREAD

**Issue by vasikgreif** [mailerlite/mailerlite-api-v2-php-sdk#8]
When trying to add a subscriber, I got:

```
<b>Fatal error</b>:  Uncaught exception 'Http\Client\Exception\NetworkException' in /data/www/wp-content/plugins/cf-mailerlite/vendor/php-http/curl-client/src/Client.php:134
```

I had to change the `BASE_URL` constant to `https://api.mailerlite.com/api/` to make this work, as otherwise the `CURLE_SSL_CONNECT_ERROR` was triggered.

**Comment by justinasposiunas** [comment]
Hey, good point, thanks for it! I have changed that by default to https.
